apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: operator-framework-olm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: operator-framework-olm
    app.kubernetes.io/part-of: operator-framework-olm
  name: operator-framework-olm
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: operator-framework-olm
status:
  loadBalancer: {}
